channels:
  - conda-forge
  - bioconda
dependencies:
  - python =3.6
  - pysam =0.15.2
  - numpy =1.16.1
  - samtools =1.9
  - pandas =0.25.1
  - pysamstats =1.1.2
  - regex
  - scipy =1.2.1
  - bedtools =2.25.0
  - r-base =3.5.1
  - pyfaidx =0.5.3
  - r-xml
  - r-ggplot2
  - r-caret
  - r-e1071
  - r-randomForest
  - r-glmnet
  - r-rcolorbrewer
  - r-devtools
  - r-nnet
  - r-ParamHelpers
  - r-mlr
  - snakemake
  - vcftools
